'use client';

import { Bird } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import Link from 'next/link';

export default function WarrantCanaryPage() {
    const lastUpdated = "January 1, 2026";
    const nextUpdate = "March 1, 2026";
    const canaryText = `As of ${lastUpdated}, w3Develops has never received any secret legal process that we would be prohibited from disclosing to the public. We have never been ordered to modify our system to allow access or information gathering.\n\nThe next scheduled update for this page is on or before ${nextUpdate}.`;


    return (
        <div className="max-w-3xl mx-auto p-4 md:p-10">
            <Card className="bg-card">
                <CardHeader className="text-center">
                    <div className="mx-auto bg-primary/10 p-4 rounded-full w-fit mb-4">
                        <Bird className="h-16 w-16 text-primary" />
                    </div>
                    <CardTitle className="font-headline text-4xl">Warrant Canary</CardTitle>
                    <CardDescription className="text-lg">
                        Last Updated: {lastUpdated}
                    </CardDescription>
                </CardHeader>
                <CardContent className="text-lg space-y-6">
                    <p>
                        This is a "warrant canary." It is a statement which we will publish on a regular basis, as long as it is true. If this statement is ever removed, or if it is not updated in a timely fashion, our users should assume that we have received a secret warrant or some other legal process that we are not at liberty to discuss.
                    </p>

                    <pre className="bg-muted p-4 rounded-md text-sm whitespace-pre-wrap font-mono overflow-x-auto"><code>
                        -----BEGIN PGP SIGNED MESSAGE-----
                        <br />
                        Hash: SHA256
                        <br /><br />
                        {canaryText.split('\n').map((line, i) => (
                            <span key={i}>{line}<br/></span>
                        ))}
                        <br />
                        -----BEGIN PGP SIGNATURE-----
                        <br /><br />
                        [Your PGP signature block would go here. It's a long string of characters
                        <br />
                        generated by your PGP software when you sign the message above.]
                        <br /><br />
                        -----END PGP SIGNATURE-----
                    </code></pre>

                    <p>
                        To verify the signature above, you will need our PGP public key. You can get it from a public key server or <Link href="#" className="text-primary underline">[link to your public key file]</Link>. Then, you can use a tool like <Link href="https://www.gnupg.org/" target="_blank" rel="noopener noreferrer" className="text-primary underline">GnuPG</Link> to verify the signature of the text.
                    </p>
                    
                    <div className="text-sm text-muted-foreground pt-4">
                        <h4 className="font-semibold mb-2">What is a Warrant Canary?</h4>
                        <p>
                            Many service providers are forbidden from revealing to their users that they have been served with a secret government subpoena. A warrant canary is a colloquial term for a regularly published statement that a service provider has <span className="italic">not</span> received such a subpoena. If the canary is not updated in a timely manner, or if it is removed, the absence of the statement implies that the provider <span className="italic">has</span> received such a secret subpoena. For more information, see the <Link href="https://en.wikipedia.org/wiki/Warrant_canary" target="_blank" rel="noopener noreferrer" className="text-primary underline">Wikipedia article on Warrant Canaries</Link>.
                        </p>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
